Add App's skeleton
lambdaclass/lambcast pull request #3
Opened 2024-02-21 21:05 UTC by fborello-lambda

2024-02-21 21:58 UTC, JulianGCalderon commented on Makefile
I'd start with a more atomic Makefile. There are a few things that we don't need yet, we can expand it as we need. Maybe `deps.get` and `phx.server`is enough for now.

2024-02-22 19:13 UTC, ManuelBilbao requested changes
Please update the README including the instructions to setup and run the project on dev environment

2024-02-22 19:41 UTC, fborello-lambda commented
Makes sense, the Makefile was reduced, and the README has the minimal instructions to setup the project.

2024-02-22 19:59 UTC, JulianGCalderon submitted a review, later dismissed
👍

2024-02-22 20:47 UTC, ManuelBilbao commented on README.md
> +        --name lambcast_db \
```suggestion
        --name lambcast_db \
```

There's a trailing space on this line, which breaks the command in two. This cause an error when copy-pasting the command

2024-02-22 21:20 UTC, ManuelBilbao approved these changes

2024-02-22 21:22 UTC, JulianGCalderon approved these changes

2024-02-23 17:04 UTC, merged